# Generated by Django 4.2.11 on 2026-03-25 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (FCFA)')),
                ('equity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Part (% équité)')),
                ('roi_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ROI convenu (%)')),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée convenue (mois)')),
                ('status', models.CharField(choices=[('negotiation', 'En négociation'), ('contract_sent', 'Contrat envoyé'), ('signed', 'Contrat signé'), ('payment_pending', 'Paiement en attente'), ('paid', 'Payé'), ('active', 'Actif (en cours)'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='negotiation', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('escrow', 'Séquestre GOLDEN')], default='', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=200, verbose_name='Référence de paiement')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Commission GOLDEN (%)')),
                ('contract_url', models.URLField(blank=True, verbose_name='URL du contrat signé')),
                ('contract_sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'ordering': ['-created_at'],
            },
        ),
    ]
