# Generated by Django 4.2.11 on 2026-03-26 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0003_add_investment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_type', models.CharField(choices=[('initial', 'Proposition initiale'), ('counter', 'Contre-offre'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='investments.investment')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offre de négociation',
                'ordering': ['created_at'],
            },
        ),
    ]
