# Generated by Django 4.2.11 on 2026-03-25 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Accroche')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('sector', models.CharField(choices=[('agro', 'Agro-industrie'), ('tech', 'Technologie'), ('energy', 'Énergie'), ('health', 'Santé'), ('education', 'Éducation'), ('real_estate', 'Immobilier'), ('transport', 'Transport'), ('commerce', 'Commerce'), ('finance', 'Finance'), ('tourism', 'Tourisme'), ('crafts', 'Artisanat'), ('other', 'Autre')], max_length=20, verbose_name='Secteur')),
                ('country', models.CharField(default='Bénin', max_length=100, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/%Y/%m/')),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant recherché (FCFA)')),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant levé (FCFA)')),
                ('roi_estimated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ROI estimé (%)')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investissement minimum (FCFA)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de validation'), ('active', 'Actif'), ('funded', 'Financé'), ('closed', 'Clôturé'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=10)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('interest_count', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('business_plan', 'Business Plan'), ('financial_stmt', 'États financiers'), ('license', 'Licence / Autorisation'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='projects/documents/%Y/%m/')),
                ('is_public', models.BooleanField(default=False, help_text='Visible sans être connecté si True')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favori',
            },
        ),
        migrations.CreateModel(
            name='ProjectShareToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Token de partage',
                'ordering': ['-created_at'],
            },
        ),
    ]
