# Generated by Django 4.2.11 on 2026-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_project_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfavorite',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note privée'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
