# Generated by Django 4.2.11 on 2026-03-25 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('country', models.CharField(blank=True, default='Bénin', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('porteur', 'Porteur de projet'), ('investisseur', 'Investisseur'), ('admin', 'Administrateur')], default='porteur', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('not_submitted', 'Non soumis'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='not_submitted', max_length=20)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_notes', models.TextField(blank=True)),
                ('preferred_sectors', models.JSONField(blank=True, default=list)),
                ('preferred_countries', models.JSONField(blank=True, default=list)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_profile', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport'), ('selfie', 'Selfie avec pièce'), ('proof_address', 'Justificatif de domicile'), ('business_reg', 'Registre de commerce')], max_length=20)),
                ('file', models.FileField(upload_to='kyc/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document KYC',
                'verbose_name_plural': 'Documents KYC',
            },
        ),
    ]
