# Generated by Django 4.2.11 on 2026-03-25 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0, help_text='Score de 0 à 100')),
                ('criteria', models.JSONField(default=dict, help_text='Détail des critères de scoring')),
                ('is_dismissed', models.BooleanField(default=False, help_text="L'investisseur a ignoré cette recommandation")),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['-score'],
            },
        ),
    ]
